source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'


gem 'json', '~> 1.8.3'
gem 'mysql2', '~> 0.3'
gem 'kaminari', '~> 0.16'
gem 'annotate', '~> 2.6'
gem 'dalli', '~> 2.7'
gem 'kgio', '~> 2.0'
gem 'whenever', '~> 0.7', require: false
gem 'dice_bag', '~> 0.9'
gem 'rack-accept', '~> 0.4'
gem 'squeel', '~> 1.2'
gem 'active_model_serializers', '~> 0.8'
gem 'net-http-persistent', '~> 2.8'
gem 'passenger', '~> 5.0.11'
gem 'ruby-progressbar', '~>1.7.5'
gem 'activerecord-import', '~> 0.9'
gem 'actionpack-action_caching', '~> 1.1'
gem 'activesupport-json_encoder', '~> 1.1'
gem 'responders', '~> 2.0'


gem 'nokogiri', '~> 1.6.6'


group :development do
  gem 'foreman', '~> 0.57'
end

group :test do
  gem 'timecop', '~>0.7'
  gem 'cucumber-rails', '~> 1.4', require: false
  gem 'capybara', '~> 2.4'
  gem 'webmock', '~> 1.9'
  gem 'pickle', '~> 0.5'
  gem 'database_cleaner', '~> 1.4'
  gem 'json_spec', '~> 1.1'
  gem 'shoulda-matchers', '~> 2.8'
end

group :test, :development do
  gem 'pry', '~> 0.9.12'
  gem 'brakeman', '~> 3.0'
  gem 'rack-mini-profiler', '~> 0.9'
  gem 'rubocop', '~> 0.33'
  gem 'rubycritic', '~> 1.4'
  gem 'bullet', '~> 4.14'
  gem 'traceroute', '~> 0.5'
  gem 'rspec-rails', '~> 3.3'
  gem 'consistency_fail', '~> 0.3'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'simplecov', '~> 0.8.2', require: false
  gem 'simplecov-rcov', '~> 0.2.3', require: false
  gem 'simplecov-html', '~> 0.8.0', require: false
  gem 'factory_girl', '~> 4.0'
  gem 'factory_girl_rails', '~> 4.0'
end


