source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'

gem 'haml-rails', '~> 0.9'

gem 'json', '~> 1.8.3'
gem 'dice_bag', '~> 0.9'
gem 'passenger', '~> 5.0'
gem 'activesupport-json_encoder', '~> 1.1'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', '~> 0.12', platform: :ruby
  gem 'uglifier', '~> 2.7'
end

source 'https://rails-assets.org' do
  gem 'rails-assets-angular', '1.4.4'
  gem 'rails-assets-angular-resource', '1.4.4'
  gem 'rails-assets-angular-sanitize', '1.4.4'
  gem 'rails-assets-angular-ui-router', '0.2.9'
  gem 'rails-assets-ui.bootstrap', '0.13.3'
  gem 'rails-assets-es5-shim', '4.1.10'
  gem 'rails-assets-jquery-ui', '1.11.4'
  gem 'rails-assets-momentjs', '2.10.6'
end

group :development do
  gem 'better_errors', '~> 2.1'
end

group :test do
  gem 'launchy', '~> 2.4'
  gem 'with_retries', '~> 0.0'
  gem 'webmock', '~> 1.21'
end

group :development, :test do
  gem 'brakeman', '~> 3.0'
  gem 'deadweight', '~> 0.2.2'
  gem 'rubocop', '~> 0.33'
  gem 'rubycritic', '~> 1.4'
  gem 'rack-mini-profiler', '~> 0.9'
  gem 'rails_best_practices', '~> 1.15'
  gem 'bullet', '~> 4.14'
  gem 'traceroute', '~> 0.5'
  gem 'consistency_fail', '~> 0.3'
  gem 'byebug', '~> 5.0'
  gem 'capybara', '~> 2.4'
  gem 'capybara-screenshot', '~> 1.0'
  gem 'cucumber_characteristics', '~> 0.0'
  gem 'cucumber-rails', '~> 1.4', require: false
  gem 'jasmine', '2.3'
  gem 'teaspoon-jasmine', '~> 2.2'
  gem 'parallel_tests', '~> 1.5'
  gem 'poltergeist', '~> 1.6'
  gem 'pry', '~> 0.10'
  gem 'pry-nav', '~> 0.2'
  gem 'rdoc', '~> 4.2'
  gem 'rspec-rails', '~> 3.3'
  gem 'selenium-webdriver', '~> 2.46'
  gem 'shoulda-matchers', '~> 2.8'
  gem 'simplecov', '~> 0.10', require: false
  gem 'simplecov-rcov', '~> 0.2.3', require: false
  gem 'simplecov-html', '~> 0.10', require: false
  gem 'factory_girl', '~> 4.0'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'user-choices', '~> 1.1'
  gem 'mixlib-shellout', '~> 2.1'
  gem 'yard', '~> 0.8'

  gem 'nokogiri', '~> 1.6.6'

  source 'https://rails-assets.org' do
    gem 'rails-assets-angular-mocks', '1.4.4'
  end
end


